# Generated by Django 4.2.7 on 2023-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.example.com', max_length=1024, verbose_name='Email Host')),
                ('email_host_user', models.CharField(default='user@example.com', max_length=255, verbose_name='Email Host User')),
                ('email_host_password', models.CharField(max_length=255, verbose_name='Email Host Password')),
                ('email_port', models.IntegerField(default=587, verbose_name='Email Port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
            ],
            options={
                'verbose_name': 'Настройку почты',
                'verbose_name_plural': 'Настройки почты',
            },
        ),
    ]
