# Generated by Django 4.2.7 on 2023-11-30 13:53

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('ritual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=filer.fields.image.FilerImageField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_files', to=settings.FILER_IMAGE_MODEL),
            preserve_default=False,
        ),
    ]
