# Generated by Django 4.2.7 on 2023-11-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritual', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
