# Generated by Django 4.2.7 on 2023-12-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritual', '0003_alter_useraccounts_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='services',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Что входит в услугу'),
        ),
    ]
