# Generated by Django 4.2.7 on 2023-12-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ritual', '0005_alter_image_service_simpleservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ritual.simpleservice', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ritual.simpleservice', verbose_name='Услуга'),
        ),
    ]
