# Generated by Django 4.2.7 on 2023-12-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ritual', '0006_alter_question_service_alter_review_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
