# Generated by Django 4.2.7 on 2023-12-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritual', '0009_chatmessage_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Файл'),
        ),
    ]
